version: 2

models:
- name: model2
  columns:
  - conflictedColumn1
- name: model3
  columns:
  - c
- name: model
  columns:
  - a
- name: model4
  columns:
  - updatedColumn

macros:
- name: macro1
  description: desc-macro1-base
- name: macro2
  description: desc-macro2-left
- name: macro3
  description: desc-macro3-right
- name: macro4
  description: desc-macro4-leftConflict
- name: macro5
  description: desc-macro5

seeds:
- name: seed3
- name: seed4
