#this is a section for models
models:
- name: model
  columns:
   - a
- name: model2
  columns:
  - conflictedColumn1
- name: model3
  columns:
  - c
- name: model4
  columns:
  - d

macros:
- name: macro1
  description: desc-macro1-base
- name: macro2
  description: desc-macro2-left
- name: macro4
  description: desc-macro4-leftConflict
- name: macro5
  description: desc-macro5

seeds:
- name: seed3
